name: s3-download
description: Download objects from a designated bucket with a provided prefix.
inputs:
  bucket:
    description: Name of the source bucket.
    required: true
  path:
    description: One or more file or directory paths to download.
    required: true
  prefix:
    description: Prefixed to all object names.
    required: false
runs:
  using: node16
  main: ../lib/s3-upload/main.mjs
