name: ssm-send-command
description: Execute shell commands on an EC2 instance remotely.
inputs:
  command:
    description: The command to execute.
    required: true
  instance-id:
    description: ID of an EC2 instance running the SSM agent.
    required: false
  powershell:
    description: Use powershell instead of a regular shell (should be `true` for Windows).
    required: false
    default: "false"
  wait-for-agent:
    description: Wait for the SSM agent on the remote host to be online.
    required: false
    default: "false"
outputs:
  exit-code:
    description: The exit code of the remote command.
runs:
  using: node16
  main: ../lib/ssm-send-command/main.mjs
