name: s3-upload
description: Upload objects to a designated bucket with a provided prefix.
inputs:
  bucket:
    description: Name of the destination bucket.
    required: true
  path:
    description: One or more file or directory paths to upload.
    required: true
  prefix:
    description: Prefixed to all object names.
    required: false
runs:
  using: node16
  main: ../lib/s3-upload/main.mjs
