name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Configure github-actions[bot]
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Bump version
        id: bump
        run: |
          npm version patch --no-git-tag-version
          package_version=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g' \
            | xargs)
          echo "package_version=$package_version" >> $GITHUB_OUTPUT

      - name: Commit build output
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Merge build output [skip-ci]

      - name: Create release
        run: gh release create v${{ steps.bump.outputs.package_version }} --generate-notes
