name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Bump version
        id: bump
        run: |
          npm version patch --no-git-tag-version
          package_version=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g' \
            | xargs)
          echo "package_version=$package_version" >> $GITHUB_OUTPUT

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Merge build output [skip ci]" \
            --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git push

      - name: Create release
        run: gh release create v${{ steps.bump.outputs.package_version }} --generate-notes
